version: '3.2'
services:
  database:
    container_name: database
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - ${PWD}/data/postgres:/var/lib/postgresql/data
    networks:
      - nextus
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}

  # cache:
  #  container_name: cache
  #  image: redis:6
  #  ports:
  #    - '6379:6379'
  #  networks:
  #    - nextus

  directus:
    container_name: directus
    image: directus/directus:v9.0.0-rc.24
    networks:
      - nextus
    depends_on:
      # - cache
      - database
    environment:
      PUBLIC_URL: ${CMS_ROOT_PATH}
      LOG_LEVEL: 'debug'

      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      # CACHE_ENABLED: 'true'
      # CACHE_STORE: 'redis'
      # CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: ${CMS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${CMS_ADMIN_PASSWORD}

  nextjs:
    container_name: nextjs
    build: ./nextjs
    networks:
      - nextus
    depends_on:
      - directus
    volumes:
      - '${PWD}:/nextjs'
    environment:
      DIRECTUS_ADDRESS: 'http://directus:8055'
      NEXT_PUBLIC_DIRECTUS_ADDRESS: 'http://${WEBSITE_HOST}:${DEV_PORT}${CMS_ROOT_PATH}'

  nginx:
    container_name: nginx
    image: nginx
    networks:
      - nextus
    depends_on:
      - directus
      - nextjs
    volumes:
      - ./nginx:/etc/nginx/templates
      - ${PWD}/data/nginx/logs:/var/log/nginx
    ports:
      - '${DEV_PORT}:8080'
    environment:
      NGINX_HOST: ${WEBSITE_HOST}
      NGINX_PORT: 8080
      NEXTJS_PORT: 3000
      DIRECTUS_PORT: 8055

networks:
  nextus:
